package FullResource.ui;

import FullResource.core.Core;
import arc.scene.ui.layout.Table;
import mindustry.Vars;
import mindustry.gen.Icon;
import mindustry.ui.Styles;
import mindustry.ui.dialogs.BaseDialog;

public class HugUI {
    static BaseDialog dialog = new BaseDialog("full");
    public static void init() {

        Vars.ui.hudGroup.fill(t -> {
            t.button(Icon.export, Core::onClick).size(40f).tooltip(tt -> {
                tt.setBackground(Styles.black6);
                tt.label(() -> "full").pad(2f);
            });
            t.top();
            t.x = 300;
        });
        Vars.ui.hudGroup.fill(t -> {
            t.button(Icon.export, dialog::show).size(40f).tooltip(tt -> {
                tt.setBackground(Styles.black6);
                tt.label(() -> "full").pad(2f);
            });
            t.top();
            t.x = 400;
        });
        onClick();
    }

    public static void onClick() {
        Table table = new Table();
        table.image(Icon.fileTextFillSmall);
        table.image(Icon.fileTextFill);
        table.image(Icon.fileSmall);
        table.image(Icon.file);
        table.image(Icon.fileTextSmall);
        table.row();

        table.image(Icon.fileText);
        table.image(Icon.leftSmall);
        table.image(Icon.left);
        table.image(Icon.rightSmall);
        table.image(Icon.right);
        table.image(Icon.upSmall);
        table.image(Icon.up);
        table.image(Icon.downSmall);
        table.image(Icon.down);
        table.image(Icon.homeSmall);
        table.image(Icon.home);
        table.image(Icon.okSmall);
        table.image(Icon.ok);
        table.image(Icon.imageSmall);
        table.image(Icon.image);
        table.image(Icon.starSmall);
        table.image(Icon.star);
        table.image(Icon.resizeSmall);
        table.image(Icon.resize);
        table.image(Icon.wrenchSmall);
        table.image(Icon.wrench);
        table.image(Icon.githubSquareSmall);
        table.image(Icon.githubSquare);
        table.image(Icon.fileImageSmall);
        table.image(Icon.fileImage);
        table.image(Icon.addSmall);
        table.image(Icon.add);
        table.image(Icon.editSmall);
        table.image(Icon.edit);
        table.image(Icon.chartBarSmall);
        table.image(Icon.chartBar);
        table.image(Icon.planeOutlineSmall);
        table.image(Icon.planeOutline);
        table.image(Icon.filterSmall);
        table.image(Icon.filter);
        table.image(Icon.folderSmall);
        table.image(Icon.folder);
        table.image(Icon.steamSmall);
        table.image(Icon.steam);
        table.image(Icon.downOpenSmall);
        table.image(Icon.downOpen);
        table.image(Icon.leftOpenSmall);
        table.image(Icon.leftOpen);
        table.image(Icon.upOpenSmall);
        table.image(Icon.upOpen);
        table.image(Icon.mapSmall);
        table.image(Icon.map);
        table.image(Icon.rotateSmall);
        table.image(Icon.rotate);
        table.image(Icon.playSmall);
        table.image(Icon.play);
        table.image(Icon.pauseSmall);
        table.image(Icon.pause);
        table.image(Icon.listSmall);
        table.image(Icon.list);
        table.image(Icon.cancelSmall);
        table.image(Icon.cancel);
        table.image(Icon.moveSmall);
        table.image(Icon.move);
        table.image(Icon.terminalSmall);
        table.image(Icon.terminal);
        table.image(Icon.undoSmall);
        table.image(Icon.undo);
        table.image(Icon.redoSmall);
        table.image(Icon.redo);
        table.image(Icon.infoSmall);
        table.image(Icon.info);
        table.image(Icon.infoCircleSmall);
        table.image(Icon.infoCircle);
        table.image(Icon.rightOpenOutSmall);
        table.image(Icon.rightOpenOut);
        table.image(Icon.rightOpenSmall);
        table.image(Icon.rightOpen);
        table.image(Icon.wavesSmall);
        table.image(Icon.waves);
        table.image(Icon.filtersSmall);
        table.image(Icon.filters);
        table.image(Icon.layersSmall);
        table.image(Icon.layers);
        table.image(Icon.eraserSmall);
        table.image(Icon.eraser);
        table.image(Icon.bookOpenSmall);
        table.image(Icon.bookOpen);
        table.image(Icon.gridSmall);
        table.image(Icon.grid);
        table.image(Icon.flipXSmall);
        table.image(Icon.flipX);
        table.image(Icon.flipYSmall);
        table.image(Icon.flipY);
        table.image(Icon.diagonalSmall);
        table.image(Icon.diagonal);
        table.image(Icon.discordSmall);
        table.image(Icon.discord);
        table.image(Icon.boxSmall);
        table.image(Icon.box);
        table.image(Icon.redditAlienSmall);
        table.image(Icon.redditAlien);
        table.image(Icon.githubSmall);
        table.image(Icon.github);
        table.image(Icon.googleplaySmall);
        table.image(Icon.googleplay);
        table.image(Icon.androidSmall);
        table.image(Icon.android);
        table.image(Icon.trelloSmall);
        table.image(Icon.trello);
        table.image(Icon.logicSmall);
        table.image(Icon.logic);
        table.image(Icon.distributionSmall);
        table.image(Icon.distribution);
        table.image(Icon.hammerSmall);
        table.image(Icon.hammer);
        table.image(Icon.saveSmall);
        table.image(Icon.save);
        table.image(Icon.linkSmall);
        table.image(Icon.link);
        table.image(Icon.itchioSmall);
        table.image(Icon.itchio);
        table.image(Icon.lineSmall);
        table.image(Icon.line);
        table.image(Icon.adminSmall);
        table.image(Icon.admin);
        table.image(Icon.spray1Small);
        table.image(Icon.spray1);
        table.image(Icon.craftingSmall);
        table.image(Icon.crafting);
        table.image(Icon.fillSmall);
        table.image(Icon.fill);
        table.image(Icon.pasteSmall);
        table.image(Icon.paste);
        table.image(Icon.effectSmall);
        table.image(Icon.effect);
        table.image(Icon.bookSmall);
        table.image(Icon.book);
        table.image(Icon.liquidSmall);
        table.image(Icon.liquid);
        table.image(Icon.hostSmall);
        table.image(Icon.host);
        table.image(Icon.productionSmall);
        table.image(Icon.production);
        table.image(Icon.exitSmall);
        table.image(Icon.exit);
        table.image(Icon.modePvpSmall);
        table.image(Icon.modePvp);
        table.image(Icon.modeAttackSmall);
        table.image(Icon.modeAttack);
        table.image(Icon.refresh1Small);
        table.image(Icon.refresh1);
        table.image(Icon.noneSmall);
        table.image(Icon.none);
        table.image(Icon.pencilSmall);
        table.image(Icon.pencil);
        table.image(Icon.refreshSmall);
        table.image(Icon.refresh);
        table.image(Icon.modeSurvivalSmall);
        table.image(Icon.modeSurvival);
        table.image(Icon.commandRallySmall);
        table.image(Icon.commandRally);
        table.image(Icon.unitsSmall);
        table.image(Icon.units);
        table.image(Icon.commandAttackSmall);
        table.image(Icon.commandAttack);
        table.image(Icon.trashSmall);
        table.image(Icon.trash);
        table.image(Icon.chatSmall);
        table.image(Icon.chat);
        table.image(Icon.turretSmall);
        table.image(Icon.turret);
        table.image(Icon.playersSmall);
        table.image(Icon.players);
        table.image(Icon.editorSmall);
        table.image(Icon.editor);
        table.image(Icon.copySmall);
        table.image(Icon.copy);
        table.image(Icon.treeSmall);
        table.image(Icon.tree);
        table.image(Icon.lockOpenSmall);
        table.image(Icon.lockOpen);
        table.image(Icon.pickSmall);
        table.image(Icon.pick);
        table.image(Icon.exportSmall);
        table.image(Icon.export);
        table.image(Icon.downloadSmall);
        table.image(Icon.download);
        table.image(Icon.uploadSmall);
        table.image(Icon.upload);
        table.image(Icon.settingsSmall);
        table.image(Icon.settings);
        table.image(Icon.spraySmall);
        table.image(Icon.spray);
        table.image(Icon.zoomSmall);
        table.image(Icon.zoom);
        table.image(Icon.powerOldSmall);
        table.image(Icon.powerOld);
        table.image(Icon.powerSmall);
        table.image(Icon.power);
        table.image(Icon.menuSmall);
        table.image(Icon.menu);
        table.row();

        table.image(Icon.lockSmall);
        table.image(Icon.lock);
        table.image(Icon.eyeSmall);
        table.image(Icon.eye);
        table.image(Icon.eyeOffSmall);
        table.row();

        table.image(Icon.eyeOff);
        table.image(Icon.warningSmall);
        table.image(Icon.warning);
        table.image(Icon.terrainSmall);
        table.image(Icon.terrain);
        table.row();

        table.image(Icon.defenseSmall);
        table.image(Icon.defense);
        table.image(Icon.planetSmall);
        table.image(Icon.planet);
        dialog.cont.add(table);
        dialog.addCloseButton();
    }
}
